environment:
  nodejs_version: "9"
  GH_TOKEN:
    secure: fyB6CRcrHbroxaBvzN6aPHUEhHGc3ljbbTPtEqruaDVe/iO8/dZn4LOVNS/fAlSX
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@5
  - npm ci

test_script:
  - node --version
  - npm --version
  - npm run package-ci

build: off

artifacts:
  - path: 'release\Appium*.exe'
  - path: 'release\*.yml'

