environment:
  nodejs_version: "10"
  GH_TOKEN:
    secure: fyB6CRcrHbroxaBvzN6aPHUEhHGc3ljbbTPtEqruaDVe/iO8/dZn4LOVNS/fAlSX
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm ci

test_script:
  - node --version
  - npm --version
  # TODO: Add this back when electron builder problem is resolved (Dan Graham)
  #- npm run package-ci
  #- npm run test-e2e
  #- npm run package-nsis

build: off

artifacts:
  - path: 'release\Appium*.exe'
  - path: 'release\*.yml'

