name: Weekly Sync Translations job

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
      name: Install dependencies
    - run: npm run crowdin-sync
      name: Crowdin Sync
      env:
        CROWDIN_PROJECT_ID: appium-desktop
        CROWDIN_PROJECT_KEY: ${{ secrets.CROWDIN_PROJECT_KEY }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.0.0
      with:
        token: ${{ github.token }}
        commit-message: 'chore: Update translations'
        title: 'chore: Update translations'
        branch: crowdin-sync-${{ github.run_id }}
        body: 'Update Crowdin Translations: https://crowdin.com/project/appium-desktop'
